# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.fast_add <- function(a, b) {
    .Call(`_fluxcapacitor_fast_add`, a, b)
}

.fast_as_dgeMatrix <- function(x) {
    .Call(`_fluxcapacitor_fast_as_dgeMatrix`, x)
}

.fast_add2 <- function(a, b) {
    .Call(`_fluxcapacitor_fast_add2`, a, b)
}

.fast_kronecker <- function(a, b) {
    .Call(`_fluxcapacitor_fast_kronecker`, a, b)
}

.fast_kronecker_sym <- function(a, b) {
    .Call(`_fluxcapacitor_fast_kronecker_sym`, a, b)
}

.fast_add3 <- function(a_, b_) {
    .Call(`_fluxcapacitor_fast_add3`, a_, b_)
}

